name: Backfill old data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '6,16,36,46 * * * *'

jobs:
  backfill:
    runs-on: ubuntu-latest
    concurrency: crawling
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Scrape protocols
      uses: bockstaller/europarl-crawler@main
      with:
        document-type: "sessions"
        directory: "sessions"
        refresh: "--refresh"
        backfill: "--backfill"
        rules: "-r agenda_en_html daily_agenda_en_html protocol_en_html named_voting_en_html voting_overview_en_html word_protocol_en_html"
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Backfilling data: ${timestamp}" || exit 0
        git push